
services:
  woovi-mongo:
    build: ./db
    container_name: woovi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  woovi-redis:
    build: ./redis
    container_name: woovi-redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: woovi-challenge-backend-server
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - woovi-mongo
      - woovi-redis
    environment:
      - MONGO_URI=mongodb://woovi-mongo:27017/woovi-challenge
      - SECRET_KEY='woovi-challenge-secret
      - REDIS_URL=redis://woovi-redis:6379
      - REDIS_HOST=woovi-redis
      - REDIS_PORT=6379
      - WEBSITE_URL=http://felipejazz.com:3001

  frontend-server:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: woovi-challenge-frontend-server
    ports:
      - "3001:3001"
    networks:
      - backend-network
    depends_on:
      - backend-server
    enviroment:
      - GRAPHQL_ENDPOINT=http://felipejazz.com:3000/graphql
      - REGISTER_ENDPOINT=http://felipejazz.com:3000/auth/register
      - LOGIN_ENDPOINT=http://felipejazz.com:3000/auth/login

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge



