version: '3.1'

services:
  woovi-mongo:
    build: ./db
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  woovi-redis:
    build: ./redis
    container_name: woovi-redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge

