version: '3.8'

services:
  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: woovi-challenge-backend-server
    ports:
      - "3000:3000"
  frontend-server:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: woovi-challenge-frontend-server
    ports:
      - "3001:3001"



