
services:
  woovi-mongo:
    build: ./db
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  woovi-redis:
    build: ./redis
    container_name: woovi-redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: woovi-challenge-backend-server
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - woovi-mongo
      - woovi-redis

  frontend-server:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: woovi-challenge-frontend-server
    ports:
      - "3001:3001"
    networks:
      - backend-network
    depends_on:
      - backend-server

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge



